'use client'

import { Providers } from '@/context/Providers'
import './globals.css'
import type { Metadata } from 'next'
import { Open_Sans } from 'next/font/google'
import Navigation from '@/components/Navigation'
import Footer from '@/components/Footer'
import { AuthProvider } from '@/context/AuthContext'
import { usePathname, useRouter } from 'next/navigation'
import { useEffect } from 'react'

const openSans = Open_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const pathname = usePathname()
  const { push } = useRouter()
  const token = localStorage.getItem('user-token') ?? ''

  useEffect(() => {
    if (token !== '') {
      if (pathname === '/SignIn' || pathname === '/SignUp') {
        return push('/')
      }
    }
  })

  return (
    <html lang="en">
      <body className={`${openSans.className}`}>
        <Providers>
          <AuthProvider>
            <div className="light">
              <div className="flex flex-col min-h-screen w-full bg-white">
                <Navigation />
                <div className="flex-1">{children}</div>
                <Footer />
              </div>
            </div>
          </AuthProvider>
        </Providers>
      </body>
    </html>
  )
}
