import { Providers } from "@/Providers";
import "./globals.css";
import type { Metadata } from "next";
import { /* Inter */ Open_Sans } from "next/font/google";
import Navigation from "@/components/Navigation";

const openSans = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={`${openSans.className} light`}>
        <Providers>
          <div className='flex flex-col min-h-screen w-full'>
            <Navigation />
            <div className='flex-1'>{children}N</div>
            <footer className='bg-blue-400'>holaa</footer>
          </div>
        </Providers>
      </body>
    </html>
  );
}
